---
# file: roles/apache2/tasks/apache2.yml

- name: ensure apache2 is installed Debian style
  when: ansible_os_family == "Debian"
  apt: pkg=apache2-mpm-prefork state=latest
  notify:
   - start apache2
  tags:
    - webserver
    - apache2

- name: ensure apache2 is installed Debian style
  when: ansible_os_family == "RedHat"
  yum: pkg=httpd state=latest
  notify:
   - start apache2
  tags:
    - webserver
    - apache2

- name: create sites-available and sites-enabled directories
  file: state=directory path={{ item }} mode=0775 owner=root group=root
  with_items:
    - "/etc/apache2/sites-available"
    - "/etc/apache2/sites-enabled"
  tags:
    - apache2

- name: install apache2 php mod
  when: (apache2.enable_php OR apache2_defaults.enable_php) and ansible_os_family == "Debian"
  apt: pkg=libapache2-mod-php5 state=latest
  notify:
   - restart apache2
  tags:
    - apache2

- name: disable default vhost Debian style
  when: ansible_os_family == "Debian"
  file: state=absent path={{ item }}
  with_items:
    - /etc/apache2/sites-available/default
    - /etc/apache2/sites-enabled/default
  notify:
   - restart apache2
  tags:
    - webserver
    - apache2

- name: disable default-ssl vhost Debian style
  when: ansible_os_family == "Debian"
  file: state=absent path={{ item }}
  with_items:
    - /etc/apache2/sites-available/default-ssl
    - /etc/apache2/sites-enabled/default-ssl
  notify:
   - restart apache2
  tags:
    - webserver
    - apache2

- name: disable unneeded apache modules
  file: state=absent path={{ item }}
  with_items: apache2_disable_modules
  notify:
   - restart apache2
  tags:
    - webserver
    - apache2

- name: enable needed apache2 modules
  command: a2enmod {{ item }}
  with_items: apache2_enable_modules
  notify:
   - restart apache2
  tags:
    - webserver
    - apache2

- name: set apache2 ports.conf template
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify:
    - restart apache2
  tags:
    - webserver
    - apache2

- name: set apache2 apache2.conf template
  template: src=apache2.conf.j2 dest=/etc/apache2/apache2.conf
  notify:
    - restart apache2
  tags:
    - webserver
    - apache2