---
# file: roles/apache2/tasks/apache2.yml

- name: ensure apache2 is installed Debian style
  when: ansible_os_family == "Debian"
  apt: pkg=apache2-mpm-prefork state=latest
  notify:
   - start apache2
  tags:
    - apache2

- name: ensure apache2 is installed RedHat style
  when: ansible_os_family == "RedHat"
  yum: pkg=httpd state=latest
  notify:
   - start apache2
  tags:
    - apache2

- name: create sites-available and sites-enabled directories Debian style
  when: ansible_os_family == "Debian"
  file: state=directory path={{ item }} mode=0775 owner=root group=root
  with_items:
    - "/etc/apache2/sites-available"
    - "/etc/apache2/sites-enabled"
  tags:
    - apache2

- name: install apache2 php mod Debian style
  when: (apache2.enable_php) and (ansible_os_family == "Debian")
  apt: pkg=libapache2-mod-php5 state=latest
  notify:
   - restart apache2
  tags:
    - apache2

- name: disable default vhost Debian style
  when: ansible_os_family == "Debian"
  file: state=absent path={{ item }}
  with_items:
    - /etc/apache2/sites-enabled/000-default
  notify:
   - restart apache2
  tags:
    - apache2

- name: disable default-ssl vhost Debian style
  when: ansible_os_family == "Debian"
  file: state=absent path={{ item }}
  with_items:
    - /etc/apache2/sites-enabled/default-ssl
  notify:
   - restart apache2
  tags:
    - apache2

- name: disable unneeded apache modules Debian style
  when: ansible_os_family == "Debian"
  file: state=absent path={{ item }}
  with_items: apache2_disable_debian_modules
  notify:
   - restart apache2
  tags:
    - apache2

- name: enable needed apache modules Debian style
  when: ansible_os_family == "Debian"
  file: state=link path={{ item[1].path }} src={{ item[1].src }}
  with_items: apache2_enable_debian_modules|dictsort
  notify:
   - restart apache2
  tags:
    - apache2

- name: set apache2 ports.conf template Debian style
  when: ansible_os_family == "Debian"
  template: src=ports.conf.j2 dest=/etc/apache2/ports.conf
  notify:
    - restart apache2
  tags:
    - apache2

- name: set apache2 apache2.conf template Debian style
  when: ansible_os_family == "Debian"
  template: src=debian-apache2.conf.j2 dest=/etc/apache2/apache2.conf
  notify:
    - restart apache2
  tags:
    - apache2

- name: set apache2 httpd.conf template RedHat style
  when: ansible_os_family == "RedHat"
  template: src=redhat-httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify:
    - restart httpd
  tags:
    - apache2