---
# tasks file for cron
- name: Set crontab template
  template: src="crontab.j2" dest="/etc/crontab"
  tags:
    - cron
    - crontab

- name: Set anacrontab template
  template: src="anacrontab.j2" dest="/etc/anacrontab"
  tags:
    - cron
    - anacrontab

- name: Set normal cronjobs
  cron: name="{{ item.value.name }}"
        state="{{ item.value.state }}"
        backup="{{ item.value.backup }}"
        minute="{{ item.value.minute }}"
        hour="{{ item.value.hour }}"
        day="{{ item.value.day }}"
        weekday="{{ item.value.weekday }}"
        month="{{ item.value.month }}"
        user="{{ item.value.user }}"
        job="{{ item.value.job }}"
  with_dict: cron_jobs
  tags:
    - cron