---
# file: roles/mysql-server/tasks/root_user.yml

# for the first run, assume root password is empty.
- name: ensure root@localhost has password set.
  when: mysql-server.firstrun
  mysql_user: state=present name=root password={{ mysql-server.root_password }} host=localhost
  tags:
    - mysql-server
    - mysql_root_user

- name: ensure root@127.0.0.1 has password set.
  when: mysql-server.firstrun
  mysql_user: state=present name=root password={{ mysql-server.root_password }} host=127.0.0.1 login_user={{ mysql-server_root_user }} login_password={{ mysql-server.root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user

- name: ensure root@ server host name has password set.
  when: mysql-server.firstrun
  mysql_user: state=present name=root password={{ mysql-server.root_password }} host={{ ansible_hostname }} login_user={{ mysql-server_root_user }} login_password={{ mysql-server.root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user

- name: ensure root@ server host name has password set.
  when: mysql-server.firstrun
  mysql_user: state=present name=root password={{ mysql_root_password }} host="::1" login_user={{ mysql-server_root_user }} login_password={{ mysql_root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user

# when changing the root password 
- name: ensure root@localhost has password set.
  mysql-server.change_root_password
  mysql_user: state=present name=root password={{ mysql-server_root_password }} host=localhost login_user={{ mysql-server_root_user }} login_password={{ mysql-server.old_root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user

- name: ensure root@127.0.0.1 has password set.
  mysql-server.change_root_password
  mysql_user: state=present name=root password={{ mysql-server_root_password }} host=127.0.0.1 login_user={{ mysql-server_root_user }} login_password={{ mysql-server.old_root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user

- name: ensure root@ server host name has password set.
  mysql-server.change_root_password
  mysql_user: state=present name=root password={{ mysql-server_root_password }} host={{ ansible_hostname }} login_user={{ mysql-server_root_user }} login_password={{ mysql-server.old_root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user

- name: ensure root@ server host name has password set.
  mysql-server.change_root_password
  mysql_user: state=present name=root password={{ mysql-server_root_password }} host="::1" login_user={{ mysql-server_root_user }} login_password={{ mysql-server.old_root_password }} login_host=localhost
  tags:
    - mysql-server
    - mysql_root_user