---
# file: roles/tinytinyrss/tasks/main.yml
#- debug: msg={{ item[1].version }}
#  with_items: tinytinyrss_instances|dictsort
#  tags:
#    - tinytinyrssdebug

- name: ensure git is installed
  when: ansible_os_family == "Debian"
  apt: pkg=git state=latest
  tags:
    - tinytinyrss

- name: Checkout tinytinyrss into designated docroot
  git: force=yes recursive=yes version="{{ item[1].version }}" depth=1 dest="{{ item[1].docroot }}" repo="{{ item[1].repo }}"
  with_items: tinytinyrss_instances|dictsort
  tags:
    - tinytinyrss

- name: Set docroot directory permissions
  file: state=directory path="{{ item[1].docroot }}" owner={{ item[1].server_user }} group={{ item[1].server_group }} mode=0755 recurse=yes
  with_items: tinytinyrss_instances|dictsort
  tags:
    - tinytinyrss

- name: Set custom config values in config.php.
  lineinfile: regexp="{{ item.regex }}" line="{{ item.value }}" dest="{{ item[1].docroot }}/config.php"
  with_items: tinytinyrss_instances.config|dictsort
  tags:
    - tinytinyrss

#- name: Run config template
#  template: src=config.php.j2 dest={{ item[1].docroot }}/config/config.php owner={{ item[1].server_user }} group={{ item[1].server_group }} mode=0640
#  with_items: tinytinyrss_instances|dictsort
#  tags:
#    - tinytinyrss