---
# file: roles/mysql/tasks/mysql-databases.yml

# for the first run, assume root password is empty.
- name: ensure root@localhost has password set.
  when: firstrun
  mysql_user: state=present name=root password={{ mysql_root_password }} host=localhost
  tags:
    - mysql

- name: ensure root@127.0.0.1 has password set.
  when: firstrun
  mysql_user: state=present name=root password={{ mysql_root_password }} host=127.0.0.1 login_user={{ mysql_root_user }} login_password={{ mysql_root_password }} login_host=localhost
  tags:
    - mysql

- name: ensure root@ server host name has password set.
  when: firstrun
  mysql_user: state=present name=root password={{ mysql_root_password }} host={{ ansible_hostname }} login_user={{ mysql_root_user }} login_password={{ mysql_root_password }} login_host=localhost
  tags:
    - mysql

- name: ensure root@ server host name has password set.
  when: firstrun
  mysql_user: state=present name=root password={{ mysql_root_password }} host="::1" login_user={{ mysql_root_user }} login_password={{ mysql_root_password }} login_host=localhost
  tags:
    - mysql

# when changing the root password 
- name: ensure root@localhost has password set.
  when: mysql_change_root_password
  mysql_user: state=present name=root password={{ mysql_root_password }} host=localhost login_user={{ mysql_root_user }} login_password={{ mysql_old_root_password }} login_host=localhost
  tags:
    - mysql

- name: ensure root@127.0.0.1 has password set.
  when: mysql_change_root_password
  mysql_user: state=present name=root password={{ mysql_root_password }} host=127.0.0.1 login_user={{ mysql_root_user }} login_password={{ mysql_old_root_password }} login_host=localhost
  tags:
    - mysql

- name: ensure root@ server host name has password set.
  when: mysql_change_root_password
  mysql_user: state=present name=root password={{ mysql_root_password }} host={{ ansible_hostname }} login_user={{ mysql_root_user }} login_password={{ mysql_old_root_password }} login_host=localhost
  tags:
    - mysql

- name: ensure root@ server host name has password set.
  when: mysql_change_root_password
  mysql_user: state=present name=root password={{ mysql_root_password }} host="::1" login_user={{ mysql_root_user }} login_password={{ mysql_old_root_password }} login_host=localhost
  tags:
    - mysql

# create server db's
- name: ensure mysql_databases exist
  mysql_db: state=present name="{{ item.name }}" login_host="127.0.0.1" login_user="{{ mysql_root_user }}" login_password="{{ mysql_root_password }}" collation="{{ item.collation }}" encoding="{{ item.encoding }}"
  with_items: mysql_databases|default([])
  tags:
    - mysql_databases

- name: ensure database users exist
  mysql_user: state=present name={{ item.name }} password={{ item.password }} host={{ item.host }} priv={{ item.priv }} login_host={{ item.dbhost }} login_user={{ mysql_root_user }} login_password={{ mysql_root_password }}
  with_items: mysql_users|default([])
  tags:
    - mysql_users
