---
# file: roles/ufw/tasks/main.yml
# see https://wiki.archlinux.org/index.php/Uncomplicated_Firewall#Adding_other_applications
- name: ensure ufw is installed Debian style
  when: ansible_os_family == "Debian"
  apt: pkg=ufw state=latest
  tags:
    - ufw

- name: set firewall state and policy
  ufw: state="{{ ufw_default_policy.state }}" policy="{{ ufw_default_policy.policy }}"
  tags:
    - ufw

- name: set rules based on ufw_apps
  when: item.value.enabled
  ufw: name="{{ item.value.name }}" rule="{{ item.value.rule }}"
  with_dict: ufw_apps

- name: create /etc/ufw/applications.d/ansible_ufw_custom_apps
  template: src=ansible_ufw_custom_apps.j2 dest=/etc/ufw/applications.d/ansible_ufw_custom_apps
  tags:
    - ufw

- name: set rules based on ufw_custom_apps
  when: item.value.enabled
  ufw: name="{{ item.value.name }}" rule="{{ item.value.rule }}"
  with_dict: ufw_custom_apps
