---
# file: roles/ntp_client/hanlders/main.yml

- name: start ntp
  service: name={{ ntp_client_service_name }} state=started enabled=yes

- name: stop ntp
  service: name={{ ntp_client_service_name }} state=stopped enabled=no

- name: restart ntp
  service: name={{ ntp_client_service_name }} state=restarted enabled=yes